---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: any-old-app-prod
namespace: yebyen-okd4
spec:
  interval: 20m0s
  ref:
    branch: main
  secretRef:
    name: flux-secret
  url: https://github.com/kingdonb/any_old_app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: any-old-app-prod
namespace: yebyen-okd4
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: any-old-app-version
  prune: false
  sourceRef:
    kind: GitRepository
    name: any-old-app-prod
  validation: client
---
apiVersion: v1
data:
  VERSION: v1.0.0
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: any-old-app-version
  name: any-old-app-version
