---
apiVersion: v1
data:
  VERSION: 0.10.3-alpha1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: any-old-app-version
  name: any-old-app-version
  namespace: dev
---
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: dev
  name: dev
---
apiVersion: v1
data:
  VERSION: 0.10.3
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: any-old-app-version
  name: any-old-app-version
  namespace: prod
---
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: prod
  name: prod
---
apiVersion: v1
data:
  VERSION: 0.10.3-alpha1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: any-old-app-version
  name: any-old-app-version
  namespace: qa
---
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: qa
  name: qa
---
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: stg
  name: stg
---
apiVersion: v1
data:
  VERSION: 0.10.3-alpha1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: any-old-app-version
  name: any-old-app-version
  namespace: stg
---
apiVersion: v1
data:
  VERSION: 0.10.3-alpha1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: any-old-app-version
  name: any-old-app-version
  namespace: uat
---
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: uat
  name: uat
